name = "ChessEngine"
uuid = "74dba683-9cfd-4a5a-a835-4e395551c400"
authors = ["Aayush Sabharwal <aayush.sabharwal@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
